(function () {
  window.PRODUCT_CATALOG = {
    'nehii-olbog': {
      title: 'Нэхий олбог',
      title_en: 'Sheepskin Seat Pad',
      items: [
        {
          id: 'nehii-45',
          name: 'Сандлын олбог-45см',
          name_en: 'Chair Pad - 45 cm',
          image: 'images/45.jpg',
          gallery: ['images/45.jpg', 'images/white45.jpg', 'images/brown45.jpg'],
          useShowcase: true,
          price: '72,000₮',
          price_en: '72,000₮',
          sizes: ['45см (диаметр)'],
          colors: ['Байгалийн цагаан', 'Шаргал', 'Саарал', 'Бор', 'Ногоон'],
          colorImages: ['images/small round/white.jpg', 'images/small round/beige.jpg', 'images/small round/grey.jpg', 'images/small round/brown.jpg', 'images/small round/green.jpg'],
          patterns: ['Буга', 'Янгир', 'Хонь', 'Чоно', 'Үнэг', 'Өлзий хээ'],
          item_bullet1: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet1_en: 'Made from fine merino sheepskin wool.',
          item_bullet2: 'Оффис сандал, гал тогооны сандал, хүүхдийн хичээлийн сандал зэрэгт дэвсэж ашиглана.',
          item_bullet2_en: 'Suitable for office chairs, kitchen chairs, and children\'s study chairs.',
          item_bullet3: 'Хонины нэхий нь зөөлөн дулаан мэдрэмж өгөхөөс гадна, чийг татахгүй давуу талтай.',
          item_bullet3_en: 'Sheepskin provides soft warmth and is naturally moisture-resistant.',
          description: 'Нарийн ноост меронус хонины нэхийгээр урлав. Оффис сандал, гал тогооны сандал, хүүхдийн хичээлийн сандал зэрэгт дэвсэж ашиглана. Хонины нэхий нь зөөлөн дулаан мэдрэмж өгөхөөс гадна, чийг татахгүй давуу талтай.',
          description_en: 'Crafted from fine merino sheepskin. Ideal for office chairs, kitchen chairs, and children\'s study chairs. Sheepskin provides soft warmth and is naturally moisture-resistant.'
        },
        {
          id: 'nehii-90x60',
          name: 'Нэхий олбог-60*90см',
          name_en: 'Sheepskin Pad - 60*90 cm',
          image: 'images/6090.jpg',
          gallery: ['images/nehii-olbog.jpg', 'images/6090.jpg', 'images/grey.jpg', 'images/white9060deer.jpg'],
          useShowcase: true,
          price: '143,000₮',
          price_en: '143,000₮',
          sizes: ['60*90см'],
          colors: ['Байгалийн цагаан', 'Шаргал', 'Саарал', 'Бор', 'Ногоон'],
          colorImages: ['images/small round/white.jpg', 'images/small round/beige.jpg', 'images/small round/grey.jpg', 'images/small round/brown.jpg', 'images/small round/green.jpg'],
          patterns: ['Буга', 'Янгир', 'Хонь', 'Чоно', 'Үнэг', 'Өлзий хээ'],
          item_bullet1: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet1_en: 'Made from fine merino sheepskin wool.',
          item_bullet2: 'Хүүхдийн тэрэг дээр, орны хөлд, буйдан дээр, сандал дээр дэвсэж ашиглана.',
          item_bullet2_en: 'Suitable for strollers, bed sides, sofas, and chairs.',
          item_bullet3: 'Хонины нэхий нь зөөлөн дулаан мэдрэмж өгөхөөс гадна, чийг татахгүй давуу талтай.',
          item_bullet3_en: 'Sheepskin provides soft warmth and is naturally moisture-resistant.',
          description: 'Нарийн ноост меронус хонины нэхийгээр урласан 60*90см хэмжээтэй олбог. Хүүхдийн тэрэг, орны хөл, буйдан, сандал зэрэгт дэвсэж ашиглахад тохиромжтой.',
          description_en: 'A 60*90cm sheepskin pad made from fine merino wool. Ideal for strollers, beside the bed, sofas, and chairs.'
        },
        {
          id: 'nehii-180x140',
          name: 'Нэхий олбог-180*140см',
          name_en: 'Sheepskin Pad - 180*140 cm',
          image: 'images/180140.jpg',
          gallery: ['images/180140.jpg', 'images/nehii-olbog.jpg', 'images/grey.jpg'],
          useShowcase: true,
          price: '810,000₮',
          price_en: '810,000₮',
          sizes: ['180*140см'],
          colors: ['Байгалийн цагаан', 'Шаргал', 'Саарал', 'Бор', 'Ногоон'],
          colorImages: ['images/small round/white.jpg', 'images/small round/beige.jpg', 'images/small round/grey.jpg', 'images/small round/brown.jpg', 'images/small round/green.jpg'],
          patterns: ['Буга', 'Янгир', 'Хонь', 'Чоно', 'Үнэг', 'Өлзий хээ'],
          item_bullet1: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet1_en: 'Made from fine merino sheepskin wool.',
          item_bullet2: 'Буйдан дээр, орны хөлд, зочны өрөөнд, орон дээр дэвсэж ашиглана.',
          item_bullet2_en: 'Suitable for sofas, bed sides, living rooms, and as a bed layer.',
          item_bullet3: 'Хонины нэхий нь зөөлөн дулаан мэдрэмж өгөхөөс гадна, чийг татахгүй давуу талтай.',
          item_bullet3_en: 'Sheepskin provides soft warmth and is naturally moisture-resistant.',
          description: 'Нэхий олбог-180*140см, 810,000₮. Нарийн ноост меронус хонины нэхийгээр урласан бөгөөд буйдан дээр, орны хөлд, зочны өрөөнд, орон дээр дэвсэж ашиглахад тохиромжтой. Хонины нэхий нь зөөлөн дулаан мэдрэмж өгч, чийг татахгүй давуу талтай.',
          description_en: 'Sheepskin Pad 180*140 cm, 810,000₮. Crafted from fine merino sheepskin, suitable for sofas, bed sides, living rooms, and bed layering. It provides soft warmth and is naturally moisture-resistant.'
        }
      ]
    },
    'buidangiin-buteeleg': {
      title: 'Буйдангийн бүтээлэг',
      title_en: 'Sofa Cover',
      items: [
        {
          id: 'sofa-single',
          name: 'Буйдангийн бүтээлэг 180*60см',
          name_en: 'Sofa Cover 180*60 cm',
          image: 'images/18060/18060white.jpg',
          gallery: ['images/18060/18060white.jpg', 'images/18060/18060brown.jpg'],
          useShowcase: true,
          price: '286,000₮',
          price_en: '286,000₮',
          sizes: ['180*60см'],
          colors: ['Байгалийн цагаан', 'Шаргал', 'Саарал', 'Бор', 'Ногоон'],
          colorImages: ['images/small round/white.jpg', 'images/small round/beige.jpg', 'images/small round/grey.jpg', 'images/small round/brown.jpg', 'images/small round/green.jpg'],
          patterns: ['Буга', 'Янгир', 'Хонь', 'Чоно', 'Үнэг', 'Өлзий хээ'],
          item_bullet1: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet1_en: 'Made from fine merino sheepskin wool.',
          item_bullet2: '2 нэхий холбосон загвар.',
          item_bullet2_en: 'A design made by connecting two sheepskins.',
          item_bullet3: 'Буйдан дээр, орны хөлд, орон дээр дэвсэж ашиглана.',
          item_bullet3_en: 'Suitable for sofas, bed sides, and bed layering.',
          item_bullet4: 'Хонины нэхий нь зөөлөн дулаан мэдрэмж өгөхөөс гадна, чийг татахгүй давуу талтай.',
          item_bullet4_en: 'Sheepskin provides soft warmth and is naturally moisture-resistant.',
          description: 'Буйдангийн бүтээлэг 180*60см, 286,000₮. Нарийн ноост меронус хонины нэхийгээр урласан 2 нэхий холбосон загвар бөгөөд буйдан дээр, орны хөлд, орон дээр дэвсэж ашиглахад тохиромжтой. Хонины нэхий нь зөөлөн дулаан мэдрэмж өгч, чийг татахгүй давуу талтай.',
          description_en: 'Sofa Cover 180*60 cm, 286,000₮. Made from fine merino sheepskin in a two-piece connected design, suitable for sofas, bed sides, and bed layering. It provides soft warmth and is naturally moisture-resistant.'
        },
        {
          id: 'sofa-double',
          name: 'Буйдангийн бүтээлэг 240*60см',
          name_en: 'Sofa Cover 240*60 cm',
          image: 'images/18060.png',
          gallery: ['images/18060.png'],
          useShowcase: true,
          price: '390,000₮',
          price_en: '390,000₮',
          sizes: ['240*60см'],
          colors: ['Байгалийн цагаан', 'Шаргал', 'Саарал', 'Бор', 'Ногоон'],
          colorImages: ['images/small round/white.jpg', 'images/small round/beige.jpg', 'images/small round/grey.jpg', 'images/small round/brown.jpg', 'images/small round/green.jpg'],
          patterns: ['Буга', 'Янгир', 'Хонь', 'Чоно', 'Үнэг', 'Өлзий хээ'],
          item_bullet1: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet1_en: 'Made from fine merino sheepskin wool.',
          item_bullet2: '3 нэхий холбосон загвар.',
          item_bullet2_en: 'A design made by connecting three sheepskins.',
          item_bullet3: 'Буйдан дээр, орны хөлд, орон дээр дэвсэж ашиглана.',
          item_bullet3_en: 'Suitable for sofas, bed sides, and bed layering.',
          item_bullet4: 'Хонины нэхий нь зөөлөн дулаан мэдрэмж өгөхөөс гадна, чийг татахгүй давуу талтай.',
          item_bullet4_en: 'Sheepskin provides soft warmth and is naturally moisture-resistant.',
          description: 'Буйдангийн бүтээлэг 240*60см, 390,000₮. Нарийн ноост меронус хонины нэхийгээр урласан 3 нэхий холбосон загвар бөгөөд буйдан дээр, орны хөлд, орон дээр дэвсэж ашиглахад тохиромжтой. Хонины нэхий нь зөөлөн дулаан мэдрэмж өгч, чийг татахгүй давуу талтай.',
          description_en: 'Sofa Cover 240*60 cm, 390,000₮. Made from fine merino sheepskin in a three-piece connected design, suitable for sofas, bed sides, and bed layering. It provides soft warmth and is naturally moisture-resistant.'
        },
        {
          id: 'sofa-corner',
          name: 'Буйдангийн бүтээлэг-Шоотой',
          name_en: 'Sofa Cover - Corner Set',
          image: 'images/shootoi.jpg',
          useShowcase: true,
          price: 'Үнэ:\n1мкв = 360,000₮\nСтандарт 180*60см = 380,000₮',
          price_en: 'Price:\n1 sq.m = 360,000 MNT\nStandard 180*60cm = 380,000 MNT',
          item_bullet1: 'Шоотой загвар нь таны хүссэн хэмжээгээр гарах боломжтой. /Хамгийн томдоо 200*200см/',
          item_bullet1_en: 'The corner-pattern design can be made to your requested size, up to 200*200 cm.',
          item_bullet2: '1мкв = 360,000 төгрөгөөр гарна.',
          item_bullet2_en: 'Pricing starts from 360,000 MNT per square meter.',
          item_bullet3: '3 хүний суудалтай буйдангийн бүтээлгийн стандарт хэмжээ 180*60см байдаг. Үнэ: 380,000төг.',
          item_bullet3_en: 'For a 3-seat sofa, the standard size is 180*60 cm. Price: 380,000 MNT.',
          item_bullet4: 'Дэлгүүр дээр бэлэн загварууд худалдаалагдаж байна.',
          item_bullet4_en: 'Ready-made models are available in-store.',
          description: 'Шоотой загвар нь таны хүссэн хэмжээгээр гарах боломжтой (хамгийн томдоо 200*200см). 1мкв = 360,000 төгрөгөөр гарна. 3 хүний суудалтай буйдангийн бүтээлгийн стандарт хэмжээ 180*60см бөгөөд үнэ 380,000 төгрөг. Дэлгүүр дээр бэлэн загварууд худалдаалагдаж байна.',
          description_en: 'The corner-pattern model can be made in custom sizes up to 200*200 cm. Pricing is 360,000 MNT per sq.m. The standard size for a 3-seat sofa is 180*60 cm at 380,000 MNT. Ready-made models are available in-store.'
        }
      ]
    },
    'ukhriin-khom': {
      title: 'Үхрийн хөм',
      title_en: 'Cowhide Rug',
      items: [
        {
          id: 'cow-medium',
          name: 'Дундаж хэмжээтэй үхрийн хөм',
          name_en: 'Medium Cowhide Rug',
          image: 'images/cow-hide.jpg',
          gallery: ['images/cow-hide.jpg', 'images/cowhide/cowhide1 (1).jpg', 'images/cowhide/cowhide1 (2).jpg'],
          useShowcase: true,
          price: '390,000₮',
          price_en: '390,000 MNT',
          sizes: ['Дундаж хэмжээ: 170*150см'],
          item_bullet1: 'Үхрийн хөм болгон дахин давтагдашгүй өөр өөрийн өнгөтэй.',
          item_bullet1_en: 'Each cowhide rug is unique with its own one-of-a-kind color pattern.',
          item_bullet2: 'Оффисдоо, зочны өрөөнд, унтлагын өрөөнд, майханд гэх зэргээр дэвсэж ашиглана.',
          item_bullet2_en: 'Suitable for offices, living rooms, bedrooms, tents, and similar spaces.',
          item_bullet3: 'Доороос чийг татахгүй, үнэр гарахгүй.',
          item_bullet3_en: 'Does not absorb moisture from below and does not produce odor.',
          item_bullet4: 'Элдүүр маш зөөлөн учраас эвхэж хурааж авч явах боломжтой. Жин: ойролцоогоор 3-5кг.',
          item_bullet4_en: 'Because the tanned hide is very soft, it can be folded and carried easily. Weight: approximately 3-5 kg.',
          description: 'Үнэ: 390,000төг. Дундаж хэмжээ: 170*150см. Үхрийн хөм болгон дахин давтагдашгүй өөр өөрийн өнгөтэй. Оффисдоо, зочны өрөөнд, унтлагын өрөөнд, майханд гэх зэргээр дэвсэж ашиглана. Доороос чийг татахгүй, үнэр гарахгүй. Элдүүр маш зөөлөн учраас эвхэж хурааж авч явах боломжтой. Жин: ойролцоогоор 3-5кг.',
          description_en: 'Price: 390,000 MNT. Average size: 170*150 cm. Each cowhide rug is unique in color and pattern. Suitable for offices, living rooms, bedrooms, tents, and similar spaces. It does not absorb moisture from below and does not produce odor. Because the tanned hide is very soft, it can be folded and carried easily. Weight: approximately 3-5 kg.'
        },
        {
          id: 'cow-large',
          name: 'Том хэмжээтэй үхрийн хөм',
          name_en: 'Large Cowhide Rug',
          image: 'images/cowhide/cowhide1 (3).jpg',
          gallery: ['images/cowhide/cowhide1 (3).jpg', 'images/cowhide/cowhide1 (4).jpg'],
          useShowcase: true,
          price: '490,000₮',
          price_en: '490,000 MNT',
          sizes: ['Дундаж хэмжээ: 180*170см'],
          item_bullet1: 'Үхрийн хөм болгон дахин давтагдашгүй өөр өөрийн өнгөтэй.',
          item_bullet1_en: 'Each cowhide rug is unique with its own one-of-a-kind color pattern.',
          item_bullet2: 'Оффисдоо, зочны өрөөнд, унтлагын өрөөнд, майханд гэх зэргээр дэвсэж ашиглана.',
          item_bullet2_en: 'Suitable for offices, living rooms, bedrooms, tents, and similar spaces.',
          item_bullet3: 'Доороос чийг татахгүй, үнэр гарахгүй.',
          item_bullet3_en: 'Does not absorb moisture from below and does not produce odor.',
          item_bullet4: 'Элдүүр маш зөөлөн учраас эвхэж хурааж авч явах боломжтой. Жин: ойролцоогоор 4-5кг.',
          item_bullet4_en: 'Because the tanned hide is very soft, it can be folded and carried easily. Weight: approximately 4-5 kg.',
          description: 'Үнэ: 490,000төг. Дундаж хэмжээ: 180*170см. Үхрийн хөм болгон дахин давтагдашгүй өөр өөрийн өнгөтэй. Оффисдоо, зочны өрөөнд, унтлагын өрөөнд, майханд гэх зэргээр дэвсэж ашиглана. Доороос чийг татахгүй, үнэр гарахгүй. Элдүүр маш зөөлөн учраас эвхэж хурааж авч явах боломжтой. Жин: ойролцоогоор 4-5кг.',
          description_en: 'Price: 490,000 MNT. Average size: 180*170 cm. Each cowhide rug is unique in color and pattern. Suitable for offices, living rooms, bedrooms, tents, and similar spaces. It does not absorb moisture from below and does not produce odor. Because the tanned hide is very soft, it can be folded and carried easily. Weight: approximately 4-5 kg.'
        }
      ]
    },
    aksesuar: {
      title: 'Аксессуар',
      title_en: 'Accessories',
      items: [
        {
          id: 'acc-mousepad',
          name: 'Бугуйн зөөлөвчтэй Mousepad',
          name_en: 'Mousepad with Wrist Support',
          image: 'images/mousepad.jpg',
          gallery: [
            'images/mousepad.jpg'
          ],
          useShowcase: true,
          price: '25,000₮',
          price_en: '25,000 MNT',
          item_bullet1: 'Удаан цагаар компьютер дээр суудаг хүмүүст зориулан хонины нэхий болон үхрийн ширээр урлав.',
          item_bullet1_en: 'Designed for people who spend long hours at the computer, crafted with sheepskin and cowhide leather.',
          item_bullet2: 'Хонины нэхий зөөлөвч нь танд тав тухыг мэдрүүлэх болно.',
          item_bullet2_en: 'The sheepskin wrist cushion provides extra comfort.',
          item_bullet3: 'Бугуйнд ирэх ачааллыг зөөлрүүлж, удаан хэрэглээнд эвтэйхэн.',
          item_bullet3_en: 'Reduces pressure on the wrist and remains comfortable for long use.',
          description: 'Бугуйн зөөлөвчтэй Mousepad. Үнэ: 25,000төг. Удаан цагаар компьютер дээр суудаг хүмүүст зориулан хонины нэхий болон үхрийн ширээр урлав. Хонины нэхий зөөлөвч нь танд тав тухыг мэдрүүлэх болно.',
          description_en: 'Mousepad with wrist support. Price: 25,000 MNT. Designed for people who work long hours on a computer, crafted with sheepskin and cowhide leather. The sheepskin wrist cushion provides extra comfort.'
        },
        {
          id: 'acc-carnumber',
          name: 'Машины дугаар',
          name_en: 'Car Number',
          image: 'images/Carnumber.png',
          gallery: [
            'images/Carnumber.png',
            'https://via.placeholder.com/1200x900/f2eadf/3a3127?text=Car+Number+Preview+2',
            'https://via.placeholder.com/1200x900/e8dcc9/3a3127?text=Car+Number+Preview+3',
            'https://via.placeholder.com/1200x900/ddd0bc/3a3127?text=Car+Number+Preview+4'
          ],
          price: '25,000₮',
          price_en: '25,000₮',
          materials: 'Хонины нэхий, Акрил хослол',
          materials_en: 'Sheepskin and acrylic combination',
          description: 'Хонины нэхий, Акрил хослол. Та дугаараа өгөөд захиалгаар хийлгүүлээрэй. 1-2 хоногт бэлэн болно.',
          description_en: 'Sheepskin and acrylic combination. Provide your number and order it. Ready in 1-2 days.'
        },
        {
          id: 'acc-ger-tavag',
          name: 'Гэр таваг',
          name_en: 'Ger Plate',
          image: 'images/small round/accessory/ger1.jpg',
          gallery: [
            'images/small round/accessory/ger1.jpg',
            'images/small round/accessory/ger2.jpg',
            'images/small round/accessory/ger3.jpg'
          ],
          price: 'Суурийн диаметр:\n14см - 66,000₮\n18см - 88,000₮\n24см - 110,000₮',
          price_en: 'Base diameter:\n14cm - 66,000 MNT\n18cm - 88,000 MNT\n24cm - 110,000 MNT',
          sizes: ['14см', '18см', '24см'],
          item_bullet1: 'Орчлон ертөнцийн бичил загвар, орон зай, цаг хугацааны бэлэгдэл, нарны гэрлийг нааш оруулагч, галын гэрлийг гадагш дэлгэрүүлэгч байг.',
          item_bullet1_en: 'A miniature model of the universe and a symbol of space and time; may it draw in sunlight and spread the warmth of fire outward.',
          item_bullet2: 'Соёл уламжлалаа түгээн дэлгэрүүлэхээр (Дүүрэн гэр)-г бүтээлээ.',
          item_bullet2_en: 'Created as “Duuren Ger” to preserve and spread cultural heritage.',
          item_bullet3: 'Амттаны тавгаар ашиглахаас гадна бурхан тахил, даллагын сав, үнэт эдлэл, мөнгөн тэмдэгт хадгалах, бэлэг дурсгалд ашиглах боломжтой.',
          item_bullet3_en: 'Can be used as a dessert plate, for offerings and rituals, as a blessing bowl, for storing jewelry and cash, or as a souvenir gift.',
          description: 'Орчлон ертөнцийн бичил загвар, орон зай, цаг хугацааны бэлэгдэл болсон (Дүүрэн гэр) бүтээл. Амттаны таваг, бурхан тахил, даллагын сав, үнэт эдлэл болон мөнгөн тэмдэгт хадгалах, бэлэг дурсгалд ашиглах боломжтой.',
          description_en: '“Duuren Ger” is a symbolic miniature form of the universe, space, and time. It can be used as a dessert plate, for offerings, as a blessing bowl, for storing jewelry and cash, and as a souvenir gift.'
        },
        {
          id: 'acc-luggage-tag',
          name: 'Luggage tag',
          name_en: 'Luggage tag',
          image: 'images/luggagetag.png',
          gallery: [
            'images/luggagetag.png'
          ],
          useShowcase: true,
          price: '11,000₮',
          price_en: '11,000 MNT',
          item_bullet1: 'Хонины нэхийгээр хийсэн цүнхний чимэглэл.',
          item_bullet1_en: 'A sheepskin-made decorative tag for your bag.',
          item_bullet2: 'Жижигхэн зүйлд ч сэтгэл гаргахад аялал амттай болдог.',
          item_bullet2_en: 'Even small thoughtful details make travel more enjoyable.',
          item_bullet3: 'Аяллын цүнхнээсээ зүүж бусдын ачаанаас ялгаарай.',
          item_bullet3_en: 'Attach it to your luggage and easily distinguish it from others.',
          description: 'Үнэ: 11,000төг. Хонины нэхийгээр хийсэн цүнхний чимэглэл. Жижигхэн зүйлд ч сэтгэл гаргахад аялал амттай болдог. Аяллын цүнхнээсээ зүүж бусдын ачаанаас ялгаарай.',
          description_en: 'Price: 11,000 MNT. A sheepskin-made decorative tag for your bag. Even small thoughtful details make travel more enjoyable. Attach it to your luggage and distinguish it from others.'
        },
        {
          id: 'acc-car-decoration-ongi',
          name: 'Авто машины чимэглэл',
          name_en: 'Car Decoration',
          image: 'images/ongi.jpg',
          gallery: [
            'images/ongi.jpg'
          ],
          useShowcase: true,
          price: '11,000₮',
          price_en: '11,000 MNT',
          item_bullet1: 'Энэ хааны онги тамга:',
          item_bullet1_en: 'This is the Khan\'s Ongi seal symbol.',
          item_bullet2: 'Дээд талын дугуй дүрс орчлон ертөнц, нарыг илэрхийлдэг. Харин доод талын хөндлөн дүрс нь газрыг илэрхийлдэг. Голын босоо дүрс нь хүнийг илэрхийлдэг. Онги тамга нь газар тэнгэрийг холбосон хүн гэсэн утгатай.',
          item_bullet2_en: 'The top circular shape represents the universe and the sun. The lower horizontal shape represents the earth. The center vertical shape represents a human. The Ongi seal symbolizes a person connecting earth and sky.',
          item_bullet3: 'Эзэн хааны төрийн тамганы дардас: МӨНХ ТЭНГЭРИЙН ХҮЧИН ДОР ИХ МОНГОЛ УЛСЫН ДАЛАЙ ХААНЫ ЗАРЛИГ ИЛ БУЛХА ИРГЭН ДОР ХҮРВЭЭС БИШИРТҮГЭЙ, ЮУТУГАЙ.',
          item_bullet3_en: 'Imprint of the imperial state seal: Under the power of Eternal Heaven, let the decree of the Oceanic Khan of the Great Mongol State be honored and obeyed by all citizens.',
          item_bullet4: 'Эзэн хааны тамга итгэлт хүлгийг тань ивээх болтугай.',
          item_bullet4_en: 'May the imperial seal bless and protect your trusted steed.',
          description: 'Үнэ: 11,000төг. Энэ хааны онги тамга: Дээд талын дугуй дүрс орчлон ертөнц, нарыг илэрхийлдэг. Харин доод талын хөндлөн дүрс нь газрыг илэрхийлдэг. Голын босоо дүрс нь хүнийг илэрхийлдэг. Онги тамга нь газар тэнгэрийг холбосон хүн гэсэн утгатай. Эзэн хааны төрийн тамганы дардас: МӨНХ ТЭНГЭРИЙН ХҮЧИН ДОР ИХ МОНГОЛ УЛСЫН ДАЛАЙ ХААНЫ ЗАРЛИГ ИЛ БУЛХА ИРГЭН ДОР ХҮРВЭЭС БИШИРТҮГЭЙ, ЮУТУГАЙ. Эзэн хааны тамга итгэлт хүлгийг тань ивээх болтугай.',
          description_en: 'Price: 11,000 MNT. This is the Khan\'s Ongi seal symbol. The top circular shape represents the universe and the sun, the lower horizontal shape represents earth, and the center vertical shape represents a human. The Ongi seal symbolizes a person connecting earth and sky. Imprint of the imperial state seal: under the power of Eternal Heaven, let the decree of the Oceanic Khan of the Great Mongol State be honored and obeyed. May the imperial seal bless and protect your trusted steed.'
        }
      ]
    },
    'mashiny-suudal-burees': {
      title: 'Машины суудлын бүрээс',
      title_en: 'Car Seat Cover',
      items: [
        {
          id: 'car-seat-front',
          name: 'Урд суудлын бүрээс',
          name_en: 'Front Seat Cover',
          image: 'images/seatcover.jpg',
          gallery: ['images/seatcover.jpg', 'images/Frontcarseatgray.jpg'],
          useShowcase: true,
          price: '165,000₮',
          price_en: '165,000₮',
          sizes: ['1ш'],
          colors: ['Цагаан', 'Бор', 'Саарал'],
          item_bullet1: 'Хонины нэхий суудлын бүрээс нь халуунд чийг татахгүй, хүйтэнд хайрахгүй давуу талтай.',
          item_bullet1_en: 'The sheepskin seat cover does not absorb moisture in heat and does not feel harsh in cold weather.',
          item_bullet2: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet2_en: 'Made from fine merino sheepskin wool.',
          description: 'Урд суудлын бүрээс. 1ш – 165,000төг. Өнгө: Цагаан, бор, саарал. Хонины нэхий суудлын бүрээс нь халуунд чийг татахгүй, хүйтэнд хайрахгүй давуу талтай.',
          description_en: 'Front Seat Cover. 1 pc - 165,000 MNT. Color: White, Brown, Gray. The sheepskin seat cover does not absorb moisture in heat and does not feel harsh in cold weather.'
        },
        {
          id: 'car-seat-full',
          name: 'Арын суудлын бүрээс',
          name_en: 'Full Backrest Cover',
          image: 'https://via.placeholder.com/1200x900/ece3d3/2f2922?text=Full+Backrest+Car+Seat+Cover',
          useShowcase: true,
          price: '150,000₮',
          price_en: '150,000 MNT',
          sizes: ['140*60см'],
          item_bullet1: 'Зөвхөн суудлын доод хэсгийг бүрхэнэ.',
          item_bullet1_en: 'Covers only the lower seat area.',
          item_bullet2: 'Бүрээс тогтоогч резинтэй.',
          item_bullet2_en: 'Includes elastic holders to keep the cover fixed.',
          item_bullet3: 'Хонины нэхий суудлын бүрээс нь халуунд чийг татахгүй, хүйтэнд хайрахгүй давуу талтай.',
          item_bullet3_en: 'The sheepskin seat cover does not absorb moisture in heat and does not feel harsh in cold weather.',
          item_bullet4: 'Нарийн ноост меронус хонины нэхийгээр урлав.',
          item_bullet4_en: 'Made from fine merino sheepskin wool.',
          description: 'Үнэ: 150,000төг. Хэмжээ: 140*60см. Зөвхөн суудлын доод хэсгийг бүрхэнэ. Бүрээс тогтоогч резинтэй. Хонины нэхий суудлын бүрээс нь халуунд чийг татахгүй, хүйтэнд хайрахгүй давуу талтай. Нарийн ноост меронус хонины нэхийгээр урлав.',
          description_en: 'Price: 150,000 MNT. Size: 140*60 cm. Covers only the lower seat area and includes elastic holders to keep it fixed. The sheepskin seat cover does not absorb moisture in heat and does not feel harsh in cold weather. Made from fine merino sheepskin wool.'
        }
      ]
    },
    'belgiin-bagts': {
      title: 'Бэлгийн багц',
      title_en: 'Gift Set',
      items: [
        {
          id: 'gift-set-small',
          name: 'Монгол бэлэг',
          name_en: 'Mongol Gift',
          image: 'images/gift.jpg',
          useShowcase: true,
          price: '284800төг',
          price_en: '284800 MNT',
          item_bullet1: 'Нэхий олбог 90*60см - 1ш',
          item_bullet1_en: 'Sheepskin seat pad 90*60 cm - 1 pc',
          item_bullet2: 'Дүүрэн таваг 14см диаметр - 1ш',
          item_bullet2_en: 'Deep plate, 14 cm diameter - 1 pc',
          item_bullet3: 'Шимийн охь /Хос тагштай/ - 1ш',
          item_bullet3_en: 'Shimiin Okh /with pair cups/ - 1 pc',
          description: 'Монгол бэлэг багц (Багцын үнэ: 284800төг): Нэхий олбог 90*60см - 1ш, Дүүрэн таваг 14см диаметр - 1ш, Шимийн охь /Хос тагштай/ - 1ш.',
          description_en: 'Mongol gift set (Bundle price: 284800 MNT): Sheepskin seat pad 90*60 cm - 1 pc, Deep plate 14 cm diameter - 1 pc, Shimiin Okh /with pair cups/ - 1 pc.'
        }
      ]
    }
  };
})();
