-- 1) TABLES
create table if not exists public.hero_panels (
  id bigint generated by default as identity primary key,
  image_url text not null,
  sort_order int not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  badge text,
  sort_order int not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text,
  date_text text,
  summary text,
  link_url text,
  sort_order int not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id int primary key,
  mission_text text,
  address_text text,
  phone_text text,
  map_embed_url text,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id, mission_text, address_text, phone_text, map_embed_url)
values (
  1,
  'Үеэс үед өвлөгдөх үслэг бүтээгдэхүүнийг урлана.',
  'Улаанбаатар хот, Сүхбаатар дүүрэг, 1-р хороо, Сөүлийн гудамж 12',
  '72884488',
  'https://www.google.com/maps?q=Ulaanbaatar+Sukhbaatar+District&output=embed'
)
on conflict (id) do nothing;

-- 2) ENABLE RLS
alter table public.hero_panels enable row level security;
alter table public.products enable row level security;
alter table public.news enable row level security;
alter table public.site_settings enable row level security;

-- 3) PUBLIC READ POLICIES
create policy if not exists "Public can read hero_panels"
on public.hero_panels for select
using (true);

create policy if not exists "Public can read products"
on public.products for select
using (true);

create policy if not exists "Public can read news"
on public.news for select
using (true);

create policy if not exists "Public can read site_settings"
on public.site_settings for select
using (true);

-- 4) AUTHENTICATED WRITE POLICIES
create policy if not exists "Authenticated can write hero_panels"
on public.hero_panels for all
to authenticated
using (true)
with check (true);

create policy if not exists "Authenticated can write products"
on public.products for all
to authenticated
using (true)
with check (true);

create policy if not exists "Authenticated can write news"
on public.news for all
to authenticated
using (true)
with check (true);

create policy if not exists "Authenticated can write site_settings"
on public.site_settings for all
to authenticated
using (true)
with check (true);
